
name: Deploy GitHub Pages

on:
  push:
  pull_request:  
  workflow_dispatch:

concurrency:
  group: cicd-docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Git submodules
        uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0

      - name: Build LDoc documentation
        uses: lunarmodules/ldoc@v1.5.0
        with:
          args: .

      - name: Copying files
        run: |
          cp LICENSE doc/topics/LICENSE
      
      - name: Deploy documentation to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc
