name: Packaging Lua

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: packaging-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Git submodules
        uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0

      - name: Preparing build directory
        run: |
          mkdir -p build/lua/doc/../lua

      - name: Build LDoc documentation
        uses: lunarmodules/ldoc@v1.5.0
        with:
          args: .

      - name: Copying files
        run: |
          cp readme.md build/readme.md
          cp LICENSE build/LICENSE
          cp demo.lua build/demo.lua
          cp -R doc/ build/doc/
          cp -R lua/ build/lua/
          cp LICENSE build/doc/topics/LICENSE

      - name: Upload artifact (socket.7z)
        uses: actions/upload-artifact@v4
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          name: LuaJIT-Sleep
          path: build/
          compression-level: 0
          retention-days: 30
